sudo: false
language: node_js
install:
- npm ci
script:
- npm run test:ci
- npm run danger
branches:
  except:
  - gh-pages
deploy:
  provider: script
  skip_cleanup: true
  script:
  - npm run semantic-release
notifications:
  email: false
env:
  global:
  - secure: u3fKp8l39aPQTAQVwgRPXT5qk2MOBlM9u3m3YXqxOBzlE3E4H+aT6lJ2yt89ohGzlphwGU1o1LBmPFPsaU8Efno4IMQLLE/llwx6Rc1if6p0jG0PdXwra8D8kz93iFS8R9Mn5ds4DvH8ax1lLkzy07Lbm9XRmwumaLPUVZo7mP/kZM3hlzn76TzLZOUKJ7S8w6TTwMccge4gMMoLWAhT34X/VtwwxRYeUTYnXcsdPbjJPl+ih5Uest+a4dFLonb+0Hc/qlo9w4rhkYO5trbnIJIdEz6eyVyUCPPacTvRFxvZCCRJfcY1LbJnBFAw2cOjpHIMFdZx4gtQvaYv83JACp7Waje8oswpmUPYB43QYRaQ9EwN0q6u26/Z4z9LPnk2vm9f6NuSF7gOf9rei9H6/S0B0dG8dDOvo+sQ/lRsv8FDlRVVNsHxm3UGj24dwu7QJKYc05IN4xRVq5mLkDYgSBX6dOES9+NWqJtDRuDxdKBI/N8tzYpJQaoIlI5m8cOt9xrijUmt/Q86h508JiH8eqzz0iB/21aNlU5nvGpm64rMdWk0ZLn8xzAnzupyncfrceZjIVqgdy707x9iClFEu6IlazGqTbbeHROIOW2TVE3Adzc81G9k95Xe3TgFKcpICi9kyjcXUG1ziJAcgmVEd3DMqyKE1bKq9c66HCl0cXY=
  - secure: vzSqciZ7ezQVvsIhWspE32Ft5AViyTupq1nIXl5DOB5mM59qPKIe3+dlOU1xZt4fHUzEtPuDDP+GwlojxWuO+MDpsVfc4gvMWpgJC+45CHxifOCfUGhoPwCbch4nCCx3himBz3wGnT9hvsMBFfYjIpgtEkEwe1l0pX0EKz74MgeJr5KIBwN4KUviCJrib4/ysc/BVqUgnGftyK/FikCQkYsmjUDXqZh4e6IrSdSgvid4Ah3sEyfB4fSzglf5eBzoFs/2uSnNHI7yS5EOtDMFDYrjnOyOqHJqSxcISm3WebvVoyPLATvTABbtDHs231BPuy4w7aLcVxUky0reMUjMA2TTdgowB1FAS+1gWSNVXq589SslyG69EDFAUIXNgf5qTcwfZNDDhysRwiCeBfxUkCiDVfwYyNP38neMXKxYkChWOt6FmBv0wbTOVs83F0GAgwz3kMDSMKgG9rTEQmRP42+y0r00UTsXWr1M4PJ1TDIskJPAreHHhr35xpsU3rYCzAxc6cYxZJaMYJOcRcH10X+P8VZB7z/JQkhi++HM+Ah0bFCHDIjD1tBc2GGGiusFVEsXeUhcV8VpEFYut5sFv86J1YygNqwXDV+Ipg8okJI6ecwU90+gNfzVnSaEkuhVDF/QOhwNLpqezgfX+aOjclsk5NSy6J5tIQpOMiTWnjQ=
  - secure: bnUXKYk7wrPCJegjCue8Ls3SeE0qGPJd2OqentEfBIHSjrDdEitHCJgbQOOM0CU1UgF7g4GClSnGikeieiMKAHiuegeJjuEPEktNaJpNHhUGSpIqQ7Lzh/b4RXIouxnaob01ZwreyDvDJLVq89nmKnTa13duVs1bUnTlzHPq1WzU4TzmrxLHcxvxvo4IKSpbwp3pJ4wnqyaLYKOeUCEMmthsduZyHzgwpq+OYWwjgnYQdfLO/16cF+s8NgOnuUaKBc+m40k02igb+iN4HVy9/Vp1QN6vNP12WYWpqYXe1nlNiNvBcvxY9T6GvBaUkUIW6PaXYOnOCSjGyHJTJd78Fg7dAJ6OgheWwMkIXp4GohbOxISEbc1Bmn/hWwiJ4BhSpW5gC6eyoIno5xrxI6Mv4r7ag1bse7+zUlBoTXzY77pcVyM6RubT7L7WFxAFDLAj8/cgomRbC6yx+Rd/UNPFtn5enMBTwkGwkeIDH1hNFRAi/ox7HkaHHTUfQunVYRYxKe3Xlz4VPyQiYsOA1aoKcdA+F1jDmAvx5eb+HdYlreO3MAPcj8JTzvdfJlR0p+6gwFdCsPAjU21SaP7K3eBXXnrknijWkEcbcVcMYbAL8GK2wfQLnbUWh7a0VIQKsj3Z8xDaggpvcXH5yaJvEPJOMMm1ioLmVF4/YPDml9dv3X8=
