sudo: false
language: node_js
install:
- npm ci
script:
- npm run test:ci
- npm run danger
- npm pack --loglevel notice
branches:
  except:
  - gh-pages
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
notifications:
  email: false
env:
  global:
  - GIT_AUTHOR_NAME="@thi-bot"
  - GIT_COMMITTER_NAME="@thi-bot"
  - secure: EsmADnWsdS8vy6iIM2imkb4uYbd9qPWpVklo0ZcQXr6q62SsNvlIVGaDrUS18d8GbcL7vJR2kqDz8a+s2iwcgsnHPcTger/Lu415aLKbXuEVIgFTi8ZcARCeJaC1B7ZkCUUfklfmwQ2tgo9eQKX5x/AVUyUjB19r+a638Xikgj+OHdyaoFMgBnj6ZhsQ2724GxzYJwL3vq9Tj7yqFG3Kg7lQ8RocrpWJFiCe8mDFIXP5Ldf3+BuNPFKRer8r9vQqbeBwy4cOowvMNtFb3hBdCWJO/mPts1qxpa872Z2Y21BUzQm3lozycYP+1cnY4VEDHpsx7hZKdB8Ch8lZaVAuqJSdqmVG0LL5WzqPseHamydH6cfl/KXgvJAej4WZGTJVw+itDs7+pDOSF2P4U2c7T7sk+UZUyg+IOlL+aaFQNZpIgVnh4eIxImzng8volKVRHLoASsBV2Ch/8EcAR2aHAQnYSnL9RMnAVfqzHwopxjp5CyeNk50TFTYQh8Z/1yQ2qbEmGsH4xu7SBjAcUe3xZgcJ8/0DFHJM/QaCsQtOwTI5uTNwIXW2PqMzPzank/dTMFIDt/E6yHYwLMSgvNLYbMSQbosk6T+pu/5k1WnxW2A22XbTmmQoYD652uvq2+jamLb1fr6xj9v9nPGsbfJ6GDIFnG2JGDyDqj3bBH+ZUDg=
