sudo: false
language: node_js
install:
  - npm ci
script:
  - npm run test:ci
  - npm run danger
  - npm pack --loglevel notice
branches:
  except:
    - gh-pages
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
notifications:
  email: false
