sudo: false
language: node_js
install:
- npm ci
script:
- npm run test:ci
- npm run danger
- npm pack --loglevel notice
branches:
  except:
  - gh-pages
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
notifications:
  email: false
env:
  global:
    secure: iKMRc2DaXu9uMGoN5gpwW1rriLqdlyvNzogWpSuJ2oO7OTwFSen9kD7McWkNsM3wvKYC5U7K1bJiEIDlEoPAAidmhAbw95tnmlPsLxKQf69WgSwI0xVoHIfk0FamKNxMqKr2Rgay0wDY2+SlG34G7U+/egu/7hsmuNbuCebDUkNYD/RQ5Z8MYIIqJT8/PrlU6j2bM5M3CZSQlNbqZ3ytCeCm48Ume7XerbkFKFmCibTYqU7NKKOGUrvcZnA4eCScAeEF7rnl1rgQKCgRFsOpdEwd9nZ0zD1fSxqve2Jd8NHVTMrpxYtkRB6M8mP9bHJtoEx8MTFFTUfJc0q2urIRoDiQY1LHxRzeQ8pMzFpmpl5JjZXr4FS5VaLs9EUZsrev9Bbmc7Q7FBkQo3XyuHQzMx2kvY3rUOm+oGOQXFA88r6HUikTxCYH5z4tIyFdU6lvlCR5260J9lNvSH+SzIOCzGqjw6bg61ejoZ8SfkkUZYUYEYQ34veGAOZHtFhTBm3j85aeWQXFta+YWJRpwDcykDqJRk//u/2LvQekfBNfg78ajcihHIRz4zm98uh8+f5Bamk+2tMcm0VntgWJCZ4EuDWE34JR9XRVpP7xatBpKP9CVJ3E/aWf0OjqsACT/86UWET0/9KLWe8tiA17I13uVffvq9Xb1ypO73Egos0E1OA=
