sudo: false
language: node_js
install:
- npm ci
script:
- npm run test:ci
- npm run danger
- npm pack --loglevel notice
branches:
  except:
  - gh-pages
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
notifications:
  email: false
env:
  global:
    secure: ukDLZuMzN8GhQaifnSAmhOr9SF358SACCqdfbSTmcDyWTygPriF472rF2Q/icjO4t55P0AIXjv3j/ETTckMRCviyfRu2kPm/XozgDh/TmSaJ3iIW0PaGl2gFHYi3jNCFnx/3QGlSYDrctZNyQfDtvbsjJOQ8/k2D2aaZR+TQDdW14EjvQxOQOPMX+fJxxS6IBXkVd/qE2Q3p6L4iPomWqjQng6BYEcSuOJTOgAsLxOuLTWRqIzB0v+5BLowPSbfUKgPCQ4Q5yNdZrsPH/ELkXPV7/QWq5axE5tFrQKJSrNqcmow2jabOLlyYcjHOUWwBTbfGCXMXDmpmw+Ez5plJDA8VJcnfaxqXebXbkONwfaRpGhI7uoJs6vI/+3obEcVmFXKFrkgK0QkWgkkYOKIN9dP7KTFVN//Dd/DQ2JkJ/IjvaEZZS0sUWC7zmE+dXnznBOtqz8r8CPTLvXqJ+AyEBJVYVirRLmzQX15zFcytTTUscaleY0Nf1zJrhIQNoxp6pmXG+I0MpFypDwGCkvdgpNw2XsT6ahobtcOywk3Tg63WIp4UH8xDEZrvyU2IlI/qhOlmD/MmGk6VRgphdgViuOg8KQQg858iMOLKfEiReA5w71RmxgHvcLWaLPZkO/eImN1EsyaQT4+cQZn25wQhV5dOV5UAQlqa0msWwZSSTmw=
